version: "3.6"
services:
  db:
    image: "postgres:9.6.9-alpine"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    env_file: ./config/.env
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: development
    volumes:
      - .:/code
      - django-static:/var/www/django/static
    depends_on:
      - db
    networks:
      - webnet
    env_file: ./config/.env
    environment:
      DJANGO_DATABASE_HOST: db
    command: python -Wd manage.py runserver 0.0.0.0:8000

networks:
  webnet:

volumes:
  pgdata:
  django-static:
  django-media:
